### ISSUE TITLE
Teleporter

### ISSUE THREAD

**Issue by Bubbelwubbel** [chhiwe/LobbyPlus#3]

**Comment by Wertzui123** [comment]
Please add a description to your issue.

**Comment by HimmelKreis4865** [comment]
This issue will be closed if there is no description provided until 22:00.

**Comment by HimmelKreis4865** [comment]
@FlxiBoy1313  I will close this issue now, because you did not provide any description. 
Please create a new Issue if you think you know what you want to write, to tell us about your problem.
