### ISSUE TITLE
It didnt give me the items on lobby etc.

### ISSUE THREAD

**Issue by ghost** [chhiwe/LobbyPlus#4]
When I joined the server it didnt give me any items. Also the "Lobby" was in every world.. Please fix that.

**Comment by HimmelKreis4865** [comment]
Hello @DavidFlashCZ,
LobbyPlus was made for LobbyServers, so you can't use it as a per world lobby manager. 
-> That would be a bad idea, items would get lost.

If you won't get any items, please check if the file `settings.yml` exists in `plugin_data/LobbyPlus/`.

If it is existing, please check if you're using a plugin which changes inventory or clear inventory on join.
This shouldn't be an error of LobbyPlus.
If you are really sure, there's no plugin which changese inventories on join, please comment, and tell us, so we'll find a solution.

**Comment by HimmelKreis4865** [comment]
Yea, seems to be solved or invalid. I will close this issue now.
