### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by Bubbelwubbel** [chhiwe/LobbyPlus#5]
Hey,
Ich hätte mal eine frage ob es gehen würde, also beim Compass steht ja der Server Name und vllt das unter dem Name steht ob der Online ist oder Offline ist, und wenn der online ist das dann steht wie viel user Online sind, wenn ihr das ned verstanden habt, bitte meldet euch bei mir
Danke

**Comment by Wertzui123** [comment]
Eventuell.
